// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY1HUjL9p4dD09r-NaAadUr7FMQZMc1o',
    appId: '1:602198627967:web:b7dd699e23d7eafb41d14a',
    messagingSenderId: '602198627967',
    projectId: 'mobileshop-80cd6',
    authDomain: 'mobileshop-80cd6.firebaseapp.com',
    storageBucket: 'mobileshop-80cd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2K317cIzEqhbMFa1_GiHo1G95iibTLYY',
    appId: '1:602198627967:android:5ac08a58ad4f929941d14a',
    messagingSenderId: '602198627967',
    projectId: 'mobileshop-80cd6',
    storageBucket: 'mobileshop-80cd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkaXlmAYMnrRoVqsNFyoB--RBQFWD09p4',
    appId: '1:602198627967:ios:0ce98d884008380541d14a',
    messagingSenderId: '602198627967',
    projectId: 'mobileshop-80cd6',
    storageBucket: 'mobileshop-80cd6.appspot.com',
    iosBundleId: 'com.example.flutterStoreMobile',
  );
}
